environment:
  SPMeta2_NuGet_Staging_APIKey:
    secure: wDc3/dNo7jb7UNTHdOQCwub23doUQ58hAIEhpKT/8lNcQqgrjw8BBfAJiAumtKyK

# expecting 110 base tests passed under 'CI.Core' category
# everything under .NET (non-SharePoint tests) must be marked as 'CI.Core'
test:
  categories:
    only:
      - CI.Core 

clone_folder: c:\prj\m2

build_script: 
    - ps: c:\prj\m2\SPMeta2\SPMeta2.Build\build.v12.ps1

after_test:
    - ps: c:\prj\m2\SPMeta2\SPMeta2.Build\nuget.v12.ps1

artifacts:
    - path: '**\*.nupkg'