environment:
  SPMeta2_NuGet_Staging_APIKey:
    secure: wDc3/dNo7jb7UNTHdOQCwub23doUQ58hAIEhpKT/8lNcQqgrjw8BBfAJiAumtKyK

test: off

clone_folder: c:\prj\m2

build_script: 
    - ps: c:\prj\m2\SPMeta2\SPMeta2.Build\build.v12.ps1

after_build:
	- ps: c:\prj\m2\SPMeta2\SPMeta2.Build\nuget.v12.ps1

artifacts:
  - path: '**\*.nupkg'